export const PERMISSIONS = {
  USERS_CREATE: 'users.create',
  USERS_READ: 'users.read',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  ROLES_CREATE: 'roles.create',
  ROLES_READ: 'roles.read',
  ROLES_UPDATE: 'roles.update',
  CLIENTS_CREATE: 'clients.create',
  CLIENTS_READ: 'clients.read',
  CLIENTS_UPDATE: 'clients.update',
  CLIENTS_DELETE: 'clients.delete',
  LOANS_CREATE: 'loans.create',
  LOANS_READ: 'loans.read',
  LOANS_UPDATE: 'loans.update',
  LOANS_CANCEL: 'loans.cancel',
  PAYMENTS_CREATE: 'payments.create',
  PAYMENTS_READ: 'payments.read',
  EXPENSES_CREATE: 'expenses.create',
  EXPENSES_READ: 'expenses.read',
  CASH_REGISTER_OPEN: 'cashRegister.open',
  CASH_REGISTER_CLOSE: 'cashRegister.close',
  CASH_REGISTER_READ: 'cashRegister.read',
  MORA_CONFIG: 'mora.config',
  RATE_CONFIG: 'rate.config',
  REPORTS_READ: 'reports.read',
  REPORTS_EXPORT: 'reports.export',
  DASHBOARD_READ: 'dashboard.read',
  AUDIT_READ: 'audit.read',
} as const;

export type PermissionName = typeof PERMISSIONS[keyof typeof PERMISSIONS];
