export const BUSINESS_CONSTANTS = {
  DEFAULT_INSTALLMENTS: 24,
  WORK_DAYS_PER_WEEK: 6, // Mon-Sat
  GRACE_PERIOD_HOURS: 2,
  PUNISHMENT_THRESHOLD_DAYS: 45,
  BUSINESS_DAY_START_HOUR: 8,
  AUTO_CLOSE_HOUR: 23,
  AUTO_CLOSE_MINUTE: 59,
  TRAFFIC_LIGHT: {
    GREEN_MAX_DAYS: 0,
    YELLOW_MAX_DAYS: 15,
    // RED: 16+
  },
};
